services:
  rails:
    build:
      context: ./rails-app
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT_RAILS}:3000"
    depends_on:
      - db
    volumes:
      - ./rails-app:/app
    environment:
      DB_HOST: db
      DB_NAME: "${DB_NAME}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
  db:
    image: postgres
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
